// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0-devel
// 	protoc        v3.12.3
// source: api/protobuf_spec/timer.proto

package v1

import (
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// EXECUTOR CONFIGS
type Method int32

const (
	Method_GET  Method = 0
	Method_POST Method = 1
)

// Enum value maps for Method.
var (
	Method_name = map[int32]string{
		0: "GET",
		1: "POST",
	}
	Method_value = map[string]int32{
		"GET":  0,
		"POST": 1,
	}
)

func (x Method) Enum() *Method {
	p := new(Method)
	*p = x
	return p
}

func (x Method) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Method) Descriptor() protoreflect.EnumDescriptor {
	return file_api_protobuf_spec_timer_proto_enumTypes[0].Descriptor()
}

func (Method) Type() protoreflect.EnumType {
	return &file_api_protobuf_spec_timer_proto_enumTypes[0]
}

func (x Method) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Method.Descriptor instead.
func (Method) EnumDescriptor() ([]byte, []int) {
	return file_api_protobuf_spec_timer_proto_rawDescGZIP(), []int{0}
}

// TIMER
type Timer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             []byte          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Account        string          `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	ExecutionCount uint32          `protobuf:"varint,3,opt,name=execution_count,json=executionCount,proto3" json:"execution_count,omitempty"`
	Meta           *Meta           `protobuf:"bytes,4,opt,name=meta,proto3" json:"meta,omitempty"`
	TaskConfig     *TaskConfig     `protobuf:"bytes,5,opt,name=task_config,json=taskConfig,proto3" json:"task_config,omitempty"`
	ScheduleConfig *ScheduleConfig `protobuf:"bytes,6,opt,name=schedule_config,json=scheduleConfig,proto3" json:"schedule_config,omitempty"`
}

func (x *Timer) Reset() {
	*x = Timer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protobuf_spec_timer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Timer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Timer) ProtoMessage() {}

func (x *Timer) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_spec_timer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Timer.ProtoReflect.Descriptor instead.
func (*Timer) Descriptor() ([]byte, []int) {
	return file_api_protobuf_spec_timer_proto_rawDescGZIP(), []int{0}
}

func (x *Timer) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Timer) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *Timer) GetExecutionCount() uint32 {
	if x != nil {
		return x.ExecutionCount
	}
	return 0
}

func (x *Timer) GetMeta() *Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Timer) GetTaskConfig() *TaskConfig {
	if x != nil {
		return x.TaskConfig
	}
	return nil
}

func (x *Timer) GetScheduleConfig() *ScheduleConfig {
	if x != nil {
		return x.ScheduleConfig
	}
	return nil
}

type CreateTimer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             []byte          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Account        string          `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	TaskConfig     *TaskConfig     `protobuf:"bytes,3,opt,name=task_config,json=taskConfig,proto3" json:"task_config,omitempty"`
	ScheduleConfig *ScheduleConfig `protobuf:"bytes,4,opt,name=schedule_config,json=scheduleConfig,proto3" json:"schedule_config,omitempty"`
}

func (x *CreateTimer) Reset() {
	*x = CreateTimer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protobuf_spec_timer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTimer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTimer) ProtoMessage() {}

func (x *CreateTimer) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_spec_timer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTimer.ProtoReflect.Descriptor instead.
func (*CreateTimer) Descriptor() ([]byte, []int) {
	return file_api_protobuf_spec_timer_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTimer) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *CreateTimer) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *CreateTimer) GetTaskConfig() *TaskConfig {
	if x != nil {
		return x.TaskConfig
	}
	return nil
}

func (x *CreateTimer) GetScheduleConfig() *ScheduleConfig {
	if x != nil {
		return x.ScheduleConfig
	}
	return nil
}

// SCHEDULE CONFIG
type ScheduleConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to ScheduleConfig:
	//	*ScheduleConfig_CronConfig
	//	*ScheduleConfig_IntervalConfig
	ScheduleConfig isScheduleConfig_ScheduleConfig `protobuf_oneof:"schedule_config"`
}

func (x *ScheduleConfig) Reset() {
	*x = ScheduleConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protobuf_spec_timer_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScheduleConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleConfig) ProtoMessage() {}

func (x *ScheduleConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_spec_timer_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleConfig.ProtoReflect.Descriptor instead.
func (*ScheduleConfig) Descriptor() ([]byte, []int) {
	return file_api_protobuf_spec_timer_proto_rawDescGZIP(), []int{2}
}

func (m *ScheduleConfig) GetScheduleConfig() isScheduleConfig_ScheduleConfig {
	if m != nil {
		return m.ScheduleConfig
	}
	return nil
}

func (x *ScheduleConfig) GetCronConfig() *CronConfig {
	if x, ok := x.GetScheduleConfig().(*ScheduleConfig_CronConfig); ok {
		return x.CronConfig
	}
	return nil
}

func (x *ScheduleConfig) GetIntervalConfig() *IntervalConfig {
	if x, ok := x.GetScheduleConfig().(*ScheduleConfig_IntervalConfig); ok {
		return x.IntervalConfig
	}
	return nil
}

type isScheduleConfig_ScheduleConfig interface {
	isScheduleConfig_ScheduleConfig()
}

type ScheduleConfig_CronConfig struct {
	CronConfig *CronConfig `protobuf:"bytes,1,opt,name=cron_config,json=cronConfig,proto3,oneof"`
}

type ScheduleConfig_IntervalConfig struct {
	IntervalConfig *IntervalConfig `protobuf:"bytes,2,opt,name=interval_config,json=intervalConfig,proto3,oneof"`
}

func (*ScheduleConfig_CronConfig) isScheduleConfig_ScheduleConfig() {}

func (*ScheduleConfig_IntervalConfig) isScheduleConfig_ScheduleConfig() {}

// TASK CONFIG
type TaskConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to TaskConfig:
	//	*TaskConfig_HttpConfig
	TaskConfig isTaskConfig_TaskConfig `protobuf_oneof:"task_config"`
}

func (x *TaskConfig) Reset() {
	*x = TaskConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protobuf_spec_timer_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskConfig) ProtoMessage() {}

func (x *TaskConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_spec_timer_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskConfig.ProtoReflect.Descriptor instead.
func (*TaskConfig) Descriptor() ([]byte, []int) {
	return file_api_protobuf_spec_timer_proto_rawDescGZIP(), []int{3}
}

func (m *TaskConfig) GetTaskConfig() isTaskConfig_TaskConfig {
	if m != nil {
		return m.TaskConfig
	}
	return nil
}

func (x *TaskConfig) GetHttpConfig() *HTTPConfig {
	if x, ok := x.GetTaskConfig().(*TaskConfig_HttpConfig); ok {
		return x.HttpConfig
	}
	return nil
}

type isTaskConfig_TaskConfig interface {
	isTaskConfig_TaskConfig()
}

type TaskConfig_HttpConfig struct {
	HttpConfig *HTTPConfig `protobuf:"bytes,1,opt,name=http_config,json=httpConfig,proto3,oneof"`
}

func (*TaskConfig_HttpConfig) isTaskConfig_TaskConfig() {}

// META
type Meta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CreateTime *timestamp.Timestamp `protobuf:"bytes,1,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
}

func (x *Meta) Reset() {
	*x = Meta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protobuf_spec_timer_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Meta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Meta) ProtoMessage() {}

func (x *Meta) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_spec_timer_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Meta.ProtoReflect.Descriptor instead.
func (*Meta) Descriptor() ([]byte, []int) {
	return file_api_protobuf_spec_timer_proto_rawDescGZIP(), []int{4}
}

func (x *Meta) GetCreateTime() *timestamp.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

type HTTPConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url     string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Method  Method   `protobuf:"varint,2,opt,name=method,proto3,enum=executor.Method" json:"method,omitempty"`
	Body    string   `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	Headers []string `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty"`
}

func (x *HTTPConfig) Reset() {
	*x = HTTPConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protobuf_spec_timer_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HTTPConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPConfig) ProtoMessage() {}

func (x *HTTPConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_spec_timer_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPConfig.ProtoReflect.Descriptor instead.
func (*HTTPConfig) Descriptor() ([]byte, []int) {
	return file_api_protobuf_spec_timer_proto_rawDescGZIP(), []int{5}
}

func (x *HTTPConfig) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *HTTPConfig) GetMethod() Method {
	if x != nil {
		return x.Method
	}
	return Method_GET
}

func (x *HTTPConfig) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *HTTPConfig) GetHeaders() []string {
	if x != nil {
		return x.Headers
	}
	return nil
}

// SCHEDULER CONFIGS
type IntervalConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StartTime  *timestamp.Timestamp `protobuf:"bytes,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	Interval   int32                `protobuf:"varint,2,opt,name=interval,proto3" json:"interval,omitempty"`
	Executions int32                `protobuf:"zigzag32,3,opt,name=executions,proto3" json:"executions,omitempty"`
}

func (x *IntervalConfig) Reset() {
	*x = IntervalConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protobuf_spec_timer_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IntervalConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntervalConfig) ProtoMessage() {}

func (x *IntervalConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_spec_timer_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntervalConfig.ProtoReflect.Descriptor instead.
func (*IntervalConfig) Descriptor() ([]byte, []int) {
	return file_api_protobuf_spec_timer_proto_rawDescGZIP(), []int{6}
}

func (x *IntervalConfig) GetStartTime() *timestamp.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *IntervalConfig) GetInterval() int32 {
	if x != nil {
		return x.Interval
	}
	return 0
}

func (x *IntervalConfig) GetExecutions() int32 {
	if x != nil {
		return x.Executions
	}
	return 0
}

type CronConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StartTime  *timestamp.Timestamp `protobuf:"bytes,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	Cron       string               `protobuf:"bytes,2,opt,name=cron,proto3" json:"cron,omitempty"`
	Executions int32                `protobuf:"zigzag32,3,opt,name=executions,proto3" json:"executions,omitempty"`
}

func (x *CronConfig) Reset() {
	*x = CronConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protobuf_spec_timer_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CronConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CronConfig) ProtoMessage() {}

func (x *CronConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_spec_timer_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CronConfig.ProtoReflect.Descriptor instead.
func (*CronConfig) Descriptor() ([]byte, []int) {
	return file_api_protobuf_spec_timer_proto_rawDescGZIP(), []int{7}
}

func (x *CronConfig) GetStartTime() *timestamp.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *CronConfig) GetCron() string {
	if x != nil {
		return x.Cron
	}
	return ""
}

func (x *CronConfig) GetExecutions() int32 {
	if x != nil {
		return x.Executions
	}
	return 0
}

var File_api_protobuf_spec_timer_proto protoreflect.FileDescriptor

var file_api_protobuf_spec_timer_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x5f, 0x73,
	0x70, 0x65, 0x63, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x08, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x6f, 0x72, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xf8, 0x01, 0x0a, 0x05, 0x54,
	0x69, 0x6d, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x27,
	0x0a, 0x0f, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0e, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69,
	0x6f, 0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x22, 0x0a, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x6f, 0x72,
	0x2e, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x12, 0x35, 0x0a, 0x0b, 0x74,
	0x61, 0x73, 0x6b, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x6f, 0x72, 0x2e, 0x54, 0x61, 0x73, 0x6b,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x0a, 0x74, 0x61, 0x73, 0x6b, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x12, 0x41, 0x0a, 0x0f, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x5f, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x65, 0x78,
	0x65, 0x63, 0x75, 0x74, 0x6f, 0x72, 0x2e, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x0e, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22, 0xb1, 0x01, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x54, 0x69, 0x6d, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12,
	0x35, 0x0a, 0x0b, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x6f, 0x72, 0x2e,
	0x54, 0x61, 0x73, 0x6b, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x0a, 0x74, 0x61, 0x73, 0x6b,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x41, 0x0a, 0x0f, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75,
	0x6c, 0x65, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x18, 0x2e, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x6f, 0x72, 0x2e, 0x53, 0x63, 0x68, 0x65, 0x64,
	0x75, 0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x0e, 0x73, 0x63, 0x68, 0x65, 0x64,
	0x75, 0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22, 0xa1, 0x01, 0x0a, 0x0e, 0x53, 0x63,
	0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x37, 0x0a, 0x0b,
	0x63, 0x72, 0x6f, 0x6e, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x6f, 0x72, 0x2e, 0x43, 0x72, 0x6f,
	0x6e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x48, 0x00, 0x52, 0x0a, 0x63, 0x72, 0x6f, 0x6e, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x43, 0x0a, 0x0f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61,
	0x6c, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18,
	0x2e, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x6f, 0x72, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x76,
	0x61, 0x6c, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x48, 0x00, 0x52, 0x0e, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x76, 0x61, 0x6c, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x42, 0x11, 0x0a, 0x0f, 0x73, 0x63,
	0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22, 0x54, 0x0a,
	0x0a, 0x54, 0x61, 0x73, 0x6b, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x37, 0x0a, 0x0b, 0x68,
	0x74, 0x74, 0x70, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x6f, 0x72, 0x2e, 0x48, 0x54, 0x54, 0x50,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x48, 0x00, 0x52, 0x0a, 0x68, 0x74, 0x74, 0x70, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x42, 0x0d, 0x0a, 0x0b, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x22, 0x43, 0x0a, 0x04, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x3b, 0x0a, 0x0b, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x76, 0x0a, 0x0a, 0x48, 0x54, 0x54, 0x50,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x28, 0x0a, 0x06, 0x6d, 0x65, 0x74, 0x68,
	0x6f, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x65, 0x78, 0x65, 0x63, 0x75,
	0x74, 0x6f, 0x72, 0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x52, 0x06, 0x6d, 0x65, 0x74, 0x68,
	0x6f, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73,
	0x22, 0x87, 0x01, 0x0a, 0x0e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x12, 0x39, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x74, 0x69, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x12, 0x1e, 0x0a, 0x0a, 0x65, 0x78,
	0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x11, 0x52, 0x0a,
	0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x7b, 0x0a, 0x0a, 0x43, 0x72,
	0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x39, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72,
	0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54,
	0x69, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x72, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x63, 0x72, 0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x65, 0x78, 0x65, 0x63, 0x75,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x11, 0x52, 0x0a, 0x65, 0x78, 0x65,
	0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2a, 0x1b, 0x0a, 0x06, 0x4d, 0x65, 0x74, 0x68, 0x6f,
	0x64, 0x12, 0x07, 0x0a, 0x03, 0x47, 0x45, 0x54, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x50, 0x4f,
	0x53, 0x54, 0x10, 0x01, 0x42, 0x25, 0x5a, 0x23, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x6e, 0x69, 0x76, 0x69, 0x73, 0x74, 0x61, 0x2f, 0x74, 0x61, 0x73, 0x6b, 0x74,
	0x69, 0x6d, 0x65, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_api_protobuf_spec_timer_proto_rawDescOnce sync.Once
	file_api_protobuf_spec_timer_proto_rawDescData = file_api_protobuf_spec_timer_proto_rawDesc
)

func file_api_protobuf_spec_timer_proto_rawDescGZIP() []byte {
	file_api_protobuf_spec_timer_proto_rawDescOnce.Do(func() {
		file_api_protobuf_spec_timer_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_protobuf_spec_timer_proto_rawDescData)
	})
	return file_api_protobuf_spec_timer_proto_rawDescData
}

var file_api_protobuf_spec_timer_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_protobuf_spec_timer_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_protobuf_spec_timer_proto_goTypes = []interface{}{
	(Method)(0),                 // 0: executor.Method
	(*Timer)(nil),               // 1: executor.Timer
	(*CreateTimer)(nil),         // 2: executor.CreateTimer
	(*ScheduleConfig)(nil),      // 3: executor.ScheduleConfig
	(*TaskConfig)(nil),          // 4: executor.TaskConfig
	(*Meta)(nil),                // 5: executor.Meta
	(*HTTPConfig)(nil),          // 6: executor.HTTPConfig
	(*IntervalConfig)(nil),      // 7: executor.IntervalConfig
	(*CronConfig)(nil),          // 8: executor.CronConfig
	(*timestamp.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_api_protobuf_spec_timer_proto_depIdxs = []int32{
	5,  // 0: executor.Timer.meta:type_name -> executor.Meta
	4,  // 1: executor.Timer.task_config:type_name -> executor.TaskConfig
	3,  // 2: executor.Timer.schedule_config:type_name -> executor.ScheduleConfig
	4,  // 3: executor.CreateTimer.task_config:type_name -> executor.TaskConfig
	3,  // 4: executor.CreateTimer.schedule_config:type_name -> executor.ScheduleConfig
	8,  // 5: executor.ScheduleConfig.cron_config:type_name -> executor.CronConfig
	7,  // 6: executor.ScheduleConfig.interval_config:type_name -> executor.IntervalConfig
	6,  // 7: executor.TaskConfig.http_config:type_name -> executor.HTTPConfig
	9,  // 8: executor.Meta.create_time:type_name -> google.protobuf.Timestamp
	0,  // 9: executor.HTTPConfig.method:type_name -> executor.Method
	9,  // 10: executor.IntervalConfig.start_time:type_name -> google.protobuf.Timestamp
	9,  // 11: executor.CronConfig.start_time:type_name -> google.protobuf.Timestamp
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_api_protobuf_spec_timer_proto_init() }
func file_api_protobuf_spec_timer_proto_init() {
	if File_api_protobuf_spec_timer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_protobuf_spec_timer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Timer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protobuf_spec_timer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTimer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protobuf_spec_timer_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScheduleConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protobuf_spec_timer_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protobuf_spec_timer_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Meta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protobuf_spec_timer_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HTTPConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protobuf_spec_timer_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IntervalConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protobuf_spec_timer_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CronConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_api_protobuf_spec_timer_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*ScheduleConfig_CronConfig)(nil),
		(*ScheduleConfig_IntervalConfig)(nil),
	}
	file_api_protobuf_spec_timer_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*TaskConfig_HttpConfig)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_protobuf_spec_timer_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_protobuf_spec_timer_proto_goTypes,
		DependencyIndexes: file_api_protobuf_spec_timer_proto_depIdxs,
		EnumInfos:         file_api_protobuf_spec_timer_proto_enumTypes,
		MessageInfos:      file_api_protobuf_spec_timer_proto_msgTypes,
	}.Build()
	File_api_protobuf_spec_timer_proto = out.File
	file_api_protobuf_spec_timer_proto_rawDesc = nil
	file_api_protobuf_spec_timer_proto_goTypes = nil
	file_api_protobuf_spec_timer_proto_depIdxs = nil
}
